discourse_gamification:
  discourse_gamification_enabled:
    default: false
    client: true

  scorable_categories:
    type: category_list
    default: ""

  like_received_score_value:
    default: 1
  like_given_score_value:
    default: 1
  solution_score_value:
    default: 5
  solution_topic_score_value:
    default: 2
  user_invited_score_value:
    default: 10
  time_read_score_value:
    default: 1
  post_read_score_value:
    default: 1
  topic_created_score_value:
    default: 1

  score_first_reply_of_day_enabled:
    default: true
    client: true

  post_created_score_value:
    default: 2

  first_reply_of_day_score_value:
    default: 1
  flag_created_score_value:
    default: 10
  day_visited_score_value:
    default: 1
  score_day_visited_enabled:
    default: true
    client: true
  day_visited_score_reason:
    default: "day_visited"
  reaction_received_score_value:
    default: 1
  reaction_given_score_value:
    default: 1
  chat_reaction_received_score_value:
    default: 1
  chat_reaction_given_score_value:
    default: 1
  chat_message_created_score_value:
    default: 1

  score_ranking_strategy:
    default: dense_rank
    type: enum
    choices:
      - dense_rank
      - rank
      - row_number
